### ISSUE TITLE
Unit test `pucch_test` fails with SIGBUS on RPi4

### ISSUE THREAD

**Issue by JamesHagerman** [srsLTE/srsLTE#461] opened 2020-02-22 11:21 UTC
## Issue Description ##
Running `make test` or `ctest -R pucch_test` on a Raspberry Pi 4 shows 1 test failing out of 2.

## Setup Details ##
The RPi4 is running a `2020-02-13` version of Raspbian and a freshly compiled version of `srsLTE` from current master  (`d045213fb9cbf98c83c06d7c17197a9dcbfddacf`) 

## Expected Behavior ##
2 of 2 passing tests

## Actual Behaviour ##
```
ctest -R pucch_test
Test project /home/pi/dev/srsLTE/build
    Start 218: pucch_test
1/2 Test #218: pucch_test .......................Bus error***Exception:   0.04 sec
    Start 219: pucch_test_uci_cqi_decoder
2/2 Test #219: pucch_test_uci_cqi_decoder .......   Passed    0.97 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   1.04 sec

The following tests FAILED:
	218 - pucch_test (Bus error)
Errors while running CTest
```

## Additional Information ##
Running the test in gdb using `gdb ./lib/src/phy/phch/test/pucch_test` and `run -v` shows verbose logs of the test running and ends with this output:

```
[...]
[INFO]: format 5, n_pucch: 101, ncs: 3, d: 3, t_exec=24 us
[INFO]: format 5, n_pucch: 1, ncs: 6, d: 3, t_exec=25 us
[INFO]: format 5, n_pucch: 51, ncs: 6, d: 3, t_exec=25 us
[INFO]: format 5, n_pucch: 101, ncs: 6, d: 3, t_exec=25 us

Program received signal SIGBUS, Bus error.
0x0002a5d8 in srslte_scrambling_b_offset ()
```

**Comment by andrepuschmann** [comment] 2020-04-24 12:58
Thanks James for flagging that. I think the issue is fixed in the new upcoming release. We run RPi4 tests in our CI now nightly. Please reopen if its still failing for you.

**Closed by andrepuschmann** 2020-04-24 12:58 UTC
