### ISSUE TITLE
srsEnb bladeRF Tx TX failed: Operation timed out

### ISSUE THREAD

**Issue by pat-ford** [srsLTE/srsLTE#552] opened 2020-09-24 18:18 UTC
## Issue Description ##
Built here and also tried apt-get

when I run srsenb ( :~$ sudo srsenb ) I get the following output: 
`pat@worker:~$ sudo srsenb 
---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /root/.config/srslte/enb.conf...

Built in Release mode using commit f02bfe2cf on branch master.

Opening 1 channels in RF device=bladeRF with args=default
Opening bladeRF...
Set RX sampling rate 1.92 Mhz, filter BW: 1.92 Mhz

==== eNodeB started ===
Type <t> to view trace
Starting plot for worker_id=0
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Set RX sampling rate 11.52 Mhz, filter BW: 9.22 Mhz
Setting manual TX/RX offset to 27 samples
Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz for cc_idx=0
set TX frequency to 2684999998
set RX frequency to 2564999998
/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

^CStopping ..
^C^C/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

/home/pat/tools/srsLTE/lib/src/phy/rf/rf_blade_imp.c.519: TX failed: Operation timed out

Couldn't stop after 5s. Forcing exit.
Killed
`
I get the same with both prebuilt and built here versions.  If I leave it running it takes a while but it will dump. Happens with both stock config file and altered.
Backtrace 
`--- command='srsenb' version=20.04.2 signal=11 date='24/09/2020 17:14:44' ---
	srsenb(+0x11c392) [0x55a850fe3392]
	/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f5a03f61210]
	srsenb(+0x85067) [0x55a850f4c067]
	srsenb(+0x129a59) [0x55a850ff0a59]
	srsenb(+0x67293) [0x55a850f2e293]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f5a04836609]
	/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f5a0403d293]

--- command='srsenb' version=20.04.2 signal=11 date='24/09/2020 17:14:44' ---
	srsenb(+0x11c392) [0x55a850fe3392]
	/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f5a03f61210]
	srsenb(+0x85067) [0x55a850f4c067]
	srsenb(+0x129a59) [0x55a850ff0a59]
	srsenb(+0x67293) [0x55a850f2e293]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f5a04836609]
	/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f5a0403d293]

--- command='srsenb' version=20.04.2 signal=11 date='24/09/2020 17:14:44' ---
	srsenb(+0x11c392) [0x55a850fe3392]
	/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f5a03f61210]
	srsenb(+0x85067) [0x55a850f4c067]
	srsenb(+0x129a59) [0x55a850ff0a59]
	srsenb(+0x67293) [0x55a850f2e293]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f5a04836609]
	/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f5a0403d293]
`
enb.log
`17:49:03.957737 [ENB ] [I] Built in Release mode using commit f02bfe2cf on branch master.
Closing log
`
current mod'd epc.conf
`#####################################################################
#                   srsENB configuration file
#####################################################################

#####################################################################
# eNB configuration
#
# enb_id:         20-bit eNB identifier.
# mcc:            Mobile Country Code
# mnc:            Mobile Network Code
# mme_addr:       IP address of MME for S1 connnection
# gtp_bind_addr:  Local IP address to bind for GTP connection
# s1c_bind_addr:  Local IP address to bind for S1AP connection
# n_prb:          Number of Physical Resource Blocks (6,15,25,50,75,100)
# tm:             Transmission mode 1-4 (TM1 default)
# nof_ports:      Number of Tx ports (1 port default, set to 2 for TM2/3/4)
#
#####################################################################
[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
n_prb = 50
#tm = 4
#nof_ports = 2

#####################################################################
# eNB configuration files 
#
# sib_config:  SIB1, SIB2 and SIB3 configuration file 
# note: when enabling mbms, use the sib.conf.mbsfn configuration file which includes SIB13
# rr_config:   Radio Resources configuration file 
# drb_config:  DRB configuration file 
#####################################################################
[enb_files]
sib_config = sib.conf
rr_config  = rr.conf
drb_config = drb.conf

#####################################################################
# RF configuration
#
# dl_earfcn: EARFCN code for DL (only valid if a single cell is configured in rr.conf)
# tx_gain: Transmit gain (dB). 
# rx_gain: Optional receive gain (dB). If disabled, AGC if enabled
#
# Optional parameters:
# dl_freq:            Override DL frequency corresponding to dl_earfcn
# ul_freq:            Override UL frequency corresponding to dl_earfcn (must be set if dl_freq is set)
# device_name:        Device driver family. Supported options: "auto" (uses first found), "UHD" or "bladeRF" 
# device_args:        Arguments for the device driver. Options are "auto" or any string. 
#                     Default for UHD: "recv_frame_size=9232,send_frame_size=9232"
#                     Default for bladeRF: ""
# time_adv_nsamples:  Transmission time advance (in number of samples) to compensate for RF delay
#                     from antenna to timestamp insertion. 
#                     Default "auto". B210 USRP: 100 samples, bladeRF: 27.
#####################################################################
[rf]
#dl_earfcn = 3400
tx_gain = 80
rx_gain = 40

**device_name = bladeRF**

# For best performance in 2x2 MIMO and >= 15 MHz use the following device_args settings:
#     USRP B210: num_recv_frames=64,num_send_frames=64

# For best performance when BW<5 MHz (25 PRB), use the following device_args settings:
#     USRP B210: send_frame_size=512,recv_frame_size=512

#device_args = auto
**time_adv_nsamples = 27**

# Example for ZMQ-based operation with TCP transport for I/Q samples
#device_name = zmq
#device_args = fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6

***snip unchanged bits *** 

#####################################################################
[pcap]
enable = true
filename = /home/pat/tools/srsLTE/enb.pcap
s1ap_enable = true
s1ap_filename = /home/pat/tools/srsLTE/enb_s1ap.pcap

#####################################################################
# Log configuration
#
# Log levels can be set for individual layers. "all_level" sets log
# level for all layers unless otherwise configured.
# Format: e.g. phy_level = info
#
# In the same way, packet hex dumps can be limited for each level.
# "all_hex_limit" sets the hex limit for all layers unless otherwise
# configured.
# Format: e.g. phy_hex_limit = 32
#
# Logging layers: rf, phy, phy_lib, mac, rlc, pdcp, rrc, gtpu, s1ap, stack, all
# Logging levels: debug, info, warning, error, none
#
# filename: File path to use for log output. Can be set to stdout
#           to print logs to standard output
# file_max_size: Maximum file size (in kilobytes). When passed, multiple files are created.
#                If set to negative, a single log file will be created.
#####################################################################
[log]
all_level = warning
all_hex_limit = 32
filename = /home/pat/tools/srsLTE/enb.log
file_max_size = -1

[gui]
enable = true

***snip unchanged bits *** 
`

Bladerf A4 w latest fw
Occurs with both ppa and local builds from most recent git

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment] 2020-09-25 07:17
This is a duplicate of #504 I believe. Ball on this is with Nuand. Closing therefore.

**Closed by andrepuschmann** 2020-09-25 07:17 UTC

**Comment by pat-ford** [comment] 2020-09-25 15:51
The error is coming from a different area of code than #504, this is a tx timeout not rx.
